# Generated by Django 3.1.5 on 2021-05-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='folder',
            table='folders',
        ),
    ]
