# Generated by Django 3.1.5 on 2021-05-16 22:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0003_auto_20210516_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent_idx',
        ),
        migrations.AddField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folder.folder'),
        ),
    ]
