# Generated by Django 3.1.5 on 2021-05-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0004_auto_20210516_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='folder_path',
            new_name='parent_folder',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='trash_bool',
            new_name='trash_basket',
        ),
    ]
